project_id = "ybpzprgmfdbalbyaelxi"

[functions.generate-mehendi]
verify_jwt = false

[functions.generate-gallery-image]
verify_jwt = false

[functions.ahrefs-domain-rating]
verify_jwt = false

[functions.generate-mehndi-image]
verify_jwt = false

[functions.mehndi-tryon]
verify_jwt = false
